In [20]:
# Usamos la biblioteca google para poder usar archivos en nuestro drive.
from google.colab import drive
# Este comando conecta colab con drive.
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

In [103]:
# df = pd.read_csv('ruta/al/data_practice_1.csv')

import pandas as pd

# Importamos el DataFrame.
# Cargar datos desde un archivo
path = "/content/drive/MyDrive/DATA/data_practice_1.csv"
df = pd.read_csv(path, sep=";")

In [104]:
# Ver las primeras y últimas filas del DataFrame
print("Primeras filas del DataFrame:")
print(df.head())

Primeras filas del DataFrame:
  nombre_columna  columna_antigua  columna_1  columna_2  columna_orden  \
0      "manzana"               23          4         76             89
1         "pera"               23          4          6             78
2        "limon"                6          8         35              6
3      "naranja"                8         64          3             45
4       "papaya"               23          4         76             89

  Unnamed: 5
0        NaN
1        NaN
2
3        NaN
4        NaN

In [105]:
df.drop("Unnamed: 5", axis=1, inplace=True)

In [106]:

print("nÚltimas filas del DataFrame:")
print(df.tail())

nÚltimas filas del DataFrame:
   nombre_columna  columna_antigua  columna_1  columna_2  columna_orden
7         "melon"                8         64          3             45
8        "sandia"               23          4         76             89
9          "kiwi"               23          4          6             78
10         "lima"                6          8         35              6
11      "durazno"                8         64          3             45

In [107]:
# Obtener información general sobre el DataFrame
print("nInformación del DataFrame:")
print(df.info())

nInformación del DataFrame:
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 12 entries, 0 to 11
Data columns (total 5 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   nombre_columna   12 non-null     object
 1   columna_antigua  12 non-null     int64
 2   columna_1        12 non-null     int64
 3   columna_2        12 non-null     int64
 4   columna_orden    12 non-null     int64
dtypes: int64(4), object(1)
memory usage: 612.0+ bytes
None

In [108]:
# Generar estadísticas descriptivas
print("nEstadísticas descriptivas del DataFrame:")
print(df.describe())

nEstadísticas descriptivas del DataFrame:
       columna_antigua  columna_1  columna_2  columna_orden
count        12.000000  12.000000  12.000000      12.000000
mean         15.000000  20.000000  30.000000      54.500000
std           8.388304  26.587762  30.656454      33.784074
min           6.000000   4.000000   3.000000       6.000000
25%           7.500000   4.000000   5.250000      35.250000
50%          15.500000   6.000000  20.500000      61.500000
75%          23.000000  22.000000  45.250000      80.750000
max          23.000000  64.000000  76.000000      89.000000

In [109]:
# Inspeccionar los tipos de datos de las columnas
print("nTipos de datos de las columnas:")
print(df.dtypes)

nTipos de datos de las columnas:
nombre_columna     object
columna_antigua     int64
columna_1           int64
columna_2           int64
columna_orden       int64
dtype: object

In [110]:
# Contar valores únicos en una columna específica
print("nConteo de valores únicos en la columna 'nombre_columna':")
print(df['nombre_columna'].value_counts())

nConteo de valores únicos en la columna 'nombre_columna':
nombre_columna
"manzana"    1
"pera"       1
"limon"      1
"naranja"    1
"papaya"     1
"mango"      1
"guayaba"    1
"melon"      1
"sandia"     1
"kiwi"       1
"lima"       1
"durazno"    1
Name: count, dtype: int64

In [111]:
# Obtener valores únicos en una columna específica
print("nValores únicos en la columna 'nombre_columna':")
print(df['nombre_columna'].unique())

nValores únicos en la columna 'nombre_columna':
['"manzana"' '"pera"' '"limon"' '"naranja"' '"papaya"' '"mango"'
 '"guayaba"' '"melon"' '"sandia"' '"kiwi"' '"lima"' '"durazno"']

In [112]:
# Obtener el número de valores únicos en una columna específica
print("nNúmero de valores únicos en la columna 'nombre_columna':")
print(df['nombre_columna'].nunique())

nNúmero de valores únicos en la columna 'nombre_columna':
12

In [113]:
# Renombrar una columna
df.rename(columns={'columna_antigua': 'columna_nueva'}, inplace=True)
print("nDataFrame con columna renombrada:")
print(df.head())

nDataFrame con columna renombrada:
  nombre_columna  columna_nueva  columna_1  columna_2  columna_orden
0      "manzana"             23          4         76             89
1         "pera"             23          4          6             78
2        "limon"              6          8         35              6
3      "naranja"              8         64          3             45
4       "papaya"             23          4         76             89

In [114]:
# Cambiar el índice del DataFrame
df.set_index('columna_nueva', inplace=True)
print("nDataFrame con nuevo índice:")
print(df.head())

nDataFrame con nuevo índice:
              nombre_columna  columna_1  columna_2  columna_orden
columna_nueva
23                 "manzana"          4         76             89
23                    "pera"          4          6             78
6                    "limon"          8         35              6
8                  "naranja"         64          3             45
23                  "papaya"          4         76             89

In [115]:
# Ordenar el DataFrame por una columna
df_ordenado = df.sort_values(by='columna_orden')
print("nDataFrame ordenado por 'columna_orden':")
print(df_ordenado.head())

nDataFrame ordenado por 'columna_orden':
              nombre_columna  columna_1  columna_2  columna_orden
columna_nueva
6                    "limon"          8         35              6
6                  "guayaba"          8         35              6
6                     "lima"          8         35              6
8                    "melon"         64          3             45
8                  "durazno"         64          3             45

In [116]:

# Ordenar el DataFrame por múltiples columnas
df_ordenado_multi = df.sort_values(by=['columna_1', 'columna_2'], ascending=[True, False])
print("nDataFrame ordenado por 'columna_1' y 'columna_2':")
print(df_ordenado_multi.head())

nDataFrame ordenado por 'columna_1' y 'columna_2':
              nombre_columna  columna_1  columna_2  columna_orden
columna_nueva
23                 "manzana"          4         76             89
23                  "papaya"          4         76             89
23                  "sandia"          4         76             89
23                    "pera"          4          6             78
23                   "mango"          4          6             78